function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 07-Jul-2022 14:41:55

persistent Hd;

if isempty(Hd)
    
    Fpass = 0.0001;  % Passband Frequency
    Fstop = 0.0004;  % Stopband Frequency
    Apass = 1;       % Passband Ripple (dB)
    Astop = 60;      % Stopband Attenuation (dB)
    Fs    = 0.0017;  % Sampling Frequency
    
    h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    
    Hd = design(h, 'equiripple', ...
        'MinOrder', 'any', ...
        'StopbandShape', 'flat');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

